# -*- coding: utf-8 -*-
"""Relinns Technologies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVvVcW_WxfpaacmiPIlP-sUppxOiH4xd

Installation
"""

!pip install -q \
langchain \
langchain-community \
langchain-text-splitters \
langchain-huggingface \
langchain-chroma \
chromadb \
sentence-transformers \
python-dotenv \
google-generativeai \
beautifulsoup4 \
requests

from google.colab import userdata

from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

from langchain.chat_models import init_chat_model

!pip install -q langchain-google-genai
api_key = userdata.get("GEMINI_API_KEY")

model = init_chat_model(
    "google_genai:gemini-2.5-flash",
    api_key=api_key
)

print("Model initialized successfully")

urls = ["https://botpenguin.com/"]

loader = WebBaseLoader(urls)

docs = loader.load()

print("Documents loaded:", len(docs))

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    add_start_index=True
)

all_splits = text_splitter.split_documents(docs)

print("Chunks created:", len(all_splits))

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)

print("Embeddings model loaded")

vector_store = Chroma(
    collection_name="website_collection",
    embedding_function=embeddings,
    persist_directory="./chroma_db"
)

print("Vector database created")

vector_store.add_documents(
    documents=all_splits
)

print("Documents stored")

def retrieve_context(query):

    retrieved_docs = vector_store.similarity_search(
        query,
        k=3
    )

    docs_content = ""

    for doc in retrieved_docs:

        docs_content += (
            "Source: "
            + str(doc.metadata)
            + "\nContent: "
            + doc.page_content
            + "\n\n"
        )

    return docs_content, retrieved_docs

def ask_chatbot(user_query):

    context, source_docs = retrieve_context(
        user_query
    )

    if not context:
        system_message = """
You are a helpful AI assistant.
No relevant information was found to answer this question. Please state that you cannot answer the query based on the provided website content.
"""
    else:
        system_message = """
You are a helpful AI assistant.
Answer using only the provided website content.

""" + context

    messages = [
        {
            "role": "system",
            "content": system_message,
        },
        {
            "role": "user",
            "content": user_query,
        },
    ]

    response = model.invoke(messages)

    return response.content

print("Chatbot Ready!\n")

# Sample questions for demonstration
sample_questions = [
    "What is BotPenguin?",
    "What features does BotPenguin provide?",
    "Does BotPenguin support WhatsApp integration?"
]

for question in sample_questions:

    print("Question:", question)

    answer = ask_chatbot(question)

    print("\nAnswer:")
    print(answer)

    print("\n" + "-"*50 + "\n")